services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: learn_anything
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
      - ./.data/backups:/backups
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backup:
    image: postgres:latest
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data:ro
      - ./.data/backups:/backups
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: learn_anything
      PGHOST: postgres
    networks:
      - app-network
    entrypoint: |
      bash -c '
        while true; do
          BACKUP_FILE="/backups/backup_$$(date +%Y%m%d_%H%M%S).sql"
          pg_dump -h postgres -U postgres learn_anything > $$BACKUP_FILE
          gzip $$BACKUP_FILE
          echo "Backup created: $$BACKUP_FILE.gz"
          sleep 86400
        done
      '

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: